name: Docker Image CI
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Magento ${{ matrix.MAJOR_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MAJOR_VERSION:
          - "2.2"
          - "2.3"
        include:
          - MAJOR_VERSION: "2.2"
            BUILD_VERSIONS: "2.2.10 2.2.9 2.2.8"

          - MAJOR_VERSION: "2.3"
            BUILD_VERSIONS: "2.3.3 2.3.2 2.3.1 2.3.0"

    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/build.sh --push
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        BUILD_VERSIONS: ${{ matrix.BUILD_VERSIONS }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
