name: Docker Image CI
on:
  schedule:
  - cron: "0 6 * * 1"   # 6 AM UTC on Monday
  push:
    branches:
    - master

jobs:
  build:
    name: Magento ${{ matrix.MAJOR_VERSION }} (${{ matrix.MAGENTO_EDITION }})
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_DATABASE: magento
          MYSQL_USER: magento
          MYSQL_PASSWORD: magento
        options: "--name mariadb"

    strategy:
      fail-fast: false
      matrix:
        MAJOR_VERSION:
          - "2.2"
          - "2.3"
        MAGENTO_EDITION:
          - "community"
        include:
          - MAJOR_VERSION: "2.2"
            BUILD_VERSIONS: "2.2.x"
            PHP_VERSION: "7.2"
            MAGENTO_EDITION: "community"
            IMAGE_NAME: "docker.io/davidalger/magento"

          - MAJOR_VERSION: "2.3"
            BUILD_VERSIONS: "2.3.x"
            PHP_VERSION: "7.3"
            MAGENTO_EDITION: "community"
            IMAGE_NAME: "docker.io/davidalger/magento"

    steps:
    - uses: actions/checkout@v1

    - name: Build artifact
      run: ./scripts/build.sh --push
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        BUILD_VERSIONS: ${{ matrix.BUILD_VERSIONS }}
        PHP_VERSION: ${{ matrix.PHP_VERSION }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: docker.io
        MAGENTO_EDITION: ${{ matrix.MAGENTO_EDITION }}
        IMAGE_NAME: ${{ matrix.IMAGE_NAME }}

    - name: Build database
      run: |
        for suffix in "" "-sampledata"; do
          docker run --rm --network "$(docker network ls --filter 'name=github' --format '{{ .Name }}')" \
            -w /var/www/html docker.io/davidalger/magento:${{ matrix.major_version }}${suffix} \
            php bin/magento setup:install \
              --cleanup-database --db-host=mariadb --db-name=magento --db-user=magento --db-password=magento

          docker exec -it mariadb bash -c 'mysqldump -umagento -pmagento magento \
            | gzip -c > /docker-entrypoint-initdb.d/artifact.sql.gz'

          docker commit mariadb docker.io/davidalger/magento:${{ matrix.major_version }}-mariadb${suffix}
          docker image push docker.io/davidalger/magento:${{ matrix.major_version }}-mariadb${suffix}
        done
