name: Docker Image CI
on:
  schedule:
  - cron: "0 6 * * 1"   # 6 AM UTC on Monday
  push:
    branches:
    - master

jobs:
  build:
    name: Magento ${{ matrix.MAJOR_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MAJOR_VERSION:
          - "2.2"
          - "2.3"
        MAGENTO_EDITION:
          - "community"
        include:
          - MAJOR_VERSION: "2.2"
            BUILD_VERSIONS: "2.2.x"
            PHP_VERSION: "7.2"

          - MAJOR_VERSION: "2.3"
            BUILD_VERSIONS: "2.3.x"
            PHP_VERSION: "7.3"

    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/build.sh --push
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        BUILD_VERSIONS: ${{ matrix.BUILD_VERSIONS }}
        PHP_VERSION: ${{ matrix.PHP_VERSION }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
